### PR TITLE
feat: add npm-cli/settings.yml

### PR DESCRIPTION
**Pull request by wraithgar**
This will be the file that other cli repos will extend.

### CODE REVIEW

**Comment by wraithgar** [comment]
For now this is just a dump of `gh api /repos/npm/cli/labels`

**Comment by nlf** [comment]
did it not paginate the dump? i only see the `semver:major` label, but not minor or patch

**Comment by wraithgar** [comment]
*sigh* I'll go look at the api call again

**Comment by wraithgar** [comment]
Ok they should all be there.  The question now is: do we want all of these in all our repos? The cli can extend this and add the ones specific to itself.

**Comment by wraithgar** [comment]
I removed ones I thought should be repo specific.  Commit is here so you can see what was removed: https://github.com/npm/.github/pull/49/commits/e3271c64458747402ba2b7d7a0c96879bbd85475

**Review by darcyclarke — APPROVED** [review]
👍🏻

**Pull request merged**
